### This is the main way to configure the application (other than annotations).
### This file is in Yaml format but you can also configure spring boot using the traditional
### Java properties file format. 


profiles: dev

barsizesminutes:
    - 1
    - 5
    - 10

multiplierPeriods:
    - 3,7
    - 2,10

users:
    - XS2241,j69qu3zl3k8brb2k,qbkog5dnnl92oq8m7yk1lbbljfr5ris2

server:
  address: 127.0.0.1
  port: 9012

report:
  outputFolder: /Users/lalitsingh/Documents/GitHub/amit-workspace/csvOut/

historicaldata:
  day: 10