### This is the main way to configure the application (other than annotations).
### This file is in Yaml format but you can also configure spring boot using the traditional
### Java properties file format. 


profiles: dev

barsizesminute:
    - 5
    - 10
    - 15


multiplierPeriods:
    - 3,7
    - 2,10
  
data:
  mongodb:
    host: localhost
    port: 27017
    database: hc4
      
server:
  address: 127.0.0.1
  port: 9010

report:
  outputFolder: C:\data\kite\out\

historicaldata:
  day: 1