### This is the main way to configure the application (other than annotations).
### This file is in Yaml format but you can also configure spring boot using the traditional
### Java properties file format. 


spring:
  kafka:
    bootstrap-servers: ${KAFKASERVERS}
    consumer:
      zerodha-order-consume-topic: ${ORDERTICKDATAPUBLISH}
      group-id-tick: ${TICKGROUPID}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      from:
        beginning: true
        groupid: ${TICKGROUPID}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      zerodha-tick-publish-topic: ${TICKDATAPUBLISH}
      
  profiles: kubernetes
  
  data:
    mongodb:
      host: ${MONGODBHOST}
      port: 27017
      database: ${MONGODBDATABASE}
      
server:
  address: 0.0.0.0
  port: 9010
